language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip3 install -r requirements.txt
  - python3 setup.py install
script:
  - cd tests
  - python3 elementtest.py
  - python3 compoundtest.py
  - python3 reactiontest.py